# Generated by Django 4.2.8 on 2024-01-13 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coba',
            new_name='CobaSatu',
        ),
    ]
